= りあクト！ TypeScriptで始めるつらくないReact開発 第2版

https://booth.pm/ja/items/1312652

== メモ

=== 1-1.環境構築(p.17-)

* オフィシャルでは `npm install -g yarn` でのインストールを指示していない: https://stackoverflow.com/q/40025890/4506703
* `hex-ci.stylelint-plus` でなく https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint[`stylelint.vscode-stylelint`]が良いらしい: https://qiita.com/ota-meshi/items/1599fa6e7042f00635d5

=== 1-2. Hello, World!(p.20-)

* `npx create-react-app hello-world --typescript` でなく最近のドキュメントでの引数指定方法は `--template typescript`: https://qiita.com/yukihane/items/ef9c54133453e037e843

=== 2-4. クラス構文(p.31-)

____
注意点としては、コンストラクタは継承されないので constructor() と明示的に書く必要があることくらいかな。
____
コンストラクタが継承される(継承されない)、の意味が不明確。

後述サンプルコードのうち、 `FlyableBird` (`Bird` を継承している)クラスの `constructor(name)` を省略できない、ということを言いたい？むしろこのコンストラクタは冗長だと ESLint に怒られている。

* https://eslint.org/docs/rules/no-useless-constructor
* https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Classes/constructor

https://ja.reactjs.org/docs/components-and-props.html[オフィシャルのドキュメント]に一番はじめに出てくる `React.Component` 継承クラスで既にコンストラクタは存在しないし、省略不可能であると考える要素が無いように思うが。

[source,javascript]
....
class Bird {
  constructor(name) {
    this.name = name;
  }
  chirp() {
    console.log(`${this.name} が 鳴 き ま し た `);
  }
  static explain(name) {
    console.log(`${name} は 翼 が あ っ て 卵 を 生 み ま す `);
  }
}
class FlyableBird extends Bird {
  constructor(name) {
    super(name);
  }
  fly() {
    console.log(`${this.name} が 飛 び ま し た `);
  }
}
const bd1 = new Bird(" ペ ン ギ ン ");
bd1.chirp();
// ペ ン ギ ン が 鳴 き ま し た
Bird.explain(" カ ラ ス ");
// カ ラ ス は 翼 が あ っ て 卵 を 生 み ま す
const bd2 = new FlyableBird(" ス ズ メ ");
bd2.fly();
// ス ズ メ が 飛 び ま し た
....

=== 7-2. Propsをコンポーネントに受け渡す

==== `semantic.min.css` import

`semantic.min.css` を https://github.com/oukayuka/ReactBeginnersBook-2.0/blob/master/07-component/02-props/src/styles/semantic.min.css[自前で管理している](https://github.com/oukayuka/ReactBeginnersBook-2.0/blob/master/07-component/02-props/src/index.tsx#L7[import箇所]) が理由がわからない。

オフィシャルが解説している使用法は:

[quote, 'https://react.semantic-ui.com/usage[]']
____
....
import 'semantic-ui-css/semantic.min.css'
....
____

==== falsy

____
設定されてなければ参照値は undefined で false なので、
____

正確には `undefined` は `false` なのではなく https://developer.mozilla.org/ja/docs/Glossary/Falsy[`falsy`] 。

=== 7-4. コンポーネントのライフサイクル(p.93-)

hooksで `componentDidMount` のみで実行するときは、 `useEffect` の第2引数に空の配列 `[]` を渡す。
(通常は、 `componentDidMount` 相当と `componentDidUpdate` 相当)

* https://ja.reactjs.org/docs/hooks-reference.html#timing-of-effects

HooksとsetIntervalについて。はまりがちな問題がある。

* https://overreacted.io/making-setinterval-declarative-with-react-hooks/

=== 7-6. Presentational Component と Container Component(p.102-)

____
「Presentational Component はその名の通り、主に見た目を担うコンポーネントのことね。もう一方
の Container Component は処理を担うコンポーネント。Facebook で Redux や Create React App を開
発している Dan Abramov さんの記事 *5 を参考にすると、それぞれの特徴はこんな感じになる」 (以下略)
____

参照している記事 https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0[Presentational and Container Components] は2015年のものだが、次のように追記されている:

____
Update from 2019: I wrote this article a long time ago and my views have since evolved. In particular, I don’t suggest splitting your components like this anymore. If you find it natural in your codebase, this pattern can be handy.
____

=== 9-3. React Router の使い方(p.128)

==== GitHubリポジトリ誤り

*7 のリポジトリリンクが間違っている。
正しくは
https://github.com/oukayuka/ReactBeginnersBook-2.0/tree/master/09-routing/03-react-router

==== React Router の `<Route>`

React Router の `Route` を

 <Route path="/characters/:code" component={Characters} />

のように使用しているが、公式では子エレメントとして書くことを推奨している。

 <Route path="/characters/:code">
   <Characters />
 </Route>

[quote, 'https://reacttraining.com/react-router/web/api/Route']
____
The recommended method of rendering something with a <Route> is to use children elements, as shown above. There are, however, a few other methods you can use to render something with a <Route>. These are provided mostly for supporting apps that were built with earlier versions of the router before hooks were introduced.

* <Route component>
* <Route render>
* <Route children> function
____

また、URLパラメータの受け取りは 公式では(props(`RouteComponentProps`)でなく) https://reacttraining.com/react-router/web/api/Hooks/useparams[`useParams`] を使用している。
